# Generated by Django 4.2.11 on 2024-05-20 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_num', models.IntegerField(primary_key=True, serialize=False)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BYN', max_length=3)),
                ('open_date', models.DateField()),
                ('account_activity', models.BooleanField()),
                ('client_id', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.account')),
                ('overdraft_limit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.account')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.account')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.account')),
                ('social_payments', models.BooleanField(default=True)),
            ],
            bases=('accounts.account',),
        ),
    ]
